spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tx-message?useSSL=true
    username: root
    password: 1234
  redis:
    password: like
    port: 6379
    host: 192.168.194.138
server:
  port: 888
tx-lcn:
  manager:
    port: 8181